spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/book_db
      database: book_db
      clear-on-startup: false

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG